language: java
sudo: false
script: mvn clean verify
addons:
  sonarcloud:
    organization: "bartvankeersop-github"
    branches:
    - master
    - development
    - /^feature-.*$/
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
